### ISSUE TITLE
bug with self-sign certificate

### ISSUE THREAD

**Issue by ellerylee369** [KloakIT/Kloak_platform#2]
This bug is specific to my laptop though.    My system specs are as follows:

 Operating System: Windows 10 Home 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)
                 Language: English (Regional Setting: English)
      System Manufacturer: LENOVO
             System Model: 81FV
                     BIOS: 8JCN52WW (type: UEFI)
                Processor: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 CPUs), ~2.2GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16258MB RAM
                Page File: 12174MB used, 6514MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 120 DPI (125 percent)
       System DPI Setting: 120 DPI (125 percent)
          DWM DPI Scaling: UnKnown
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Supported
 DirectX Database Version: 1.1.4
           DxDiag Version: 10.00.18362.0387 64bit Unicode

The log on the command prompt is as follows:

Microsoft Windows [Version 10.0.18363.836]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\leery>ping imap.mail.me.com

Pinging imap.mail.me.com.akadns.net [17.56.8.133] with 32 bytes of data:
Request timed out.
Request timed out.

Ping statistics for 17.56.8.133:
    Packets: Sent = 2, Received = 0, Lost = 2 (100% loss),
Control-C
^C
C:\Users\leery>ns lookup imap.mail.me.com
'ns' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\leery>nslookup imap.mail.me.com
Server:  resolver1.opendns.com
Address:  208.67.222.222

Non-authoritative answer:
Name:    imap.mail.me.com.akadns.net
Address:  17.56.8.133
Aliases:  imap.mail.me.com

C:\Users\leery>F:

F:\>cd F:\Kloak Information Technologies project - NDA\test\Kloak_platform-master

F:\Kloak Information Technologies project - NDA\test\Kloak_platform-master>npm i
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated core-js@2.3.0: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

> core-js@2.6.11 postinstall F:\Kloak Information Technologies project - NDA\test\Kloak_platform-master\node_modules\babel-runtime\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> core-js@3.6.5 postinstall F:\Kloak Information Technologies project - NDA\test\Kloak_platform-master\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

> ejs@3.1.2 postinstall F:\Kloak Information Technologies project - NDA\test\Kloak_platform-master\node_modules\ejs
> node --harmony ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

> electron@8.2.5 postinstall F:\Kloak Information Technologies project - NDA\test\Kloak_platform-master\node_modules\electron
> node install.js

> nodemailer@6.4.6 postinstall F:\Kloak Information Technologies project - NDA\test\Kloak_platform-master\node_modules\nodemailer
> node -e "try{require('./postinstall')}catch(e){}"

=== Nodemailer 6.4.6 ===

Thank you for using Nodemailer for your email sending needs! While Nodemailer
itself is mostly meant to be a SMTP client there are other related projects in
the Nodemailer project as well.

For example:
> IMAP API (  https://imapapi.com  ) is a server application to easily access
IMAP accounts via REST API
> NodemailerApp (  https://nodemailer.com/app/  ) is a cross platform GUI app to
debug emails

npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> kloak_platform@0.1.10 prepublish F:\Kloak Information Technologies project - NDA\test\Kloak_platform-master
> npm run snyk-protect

> kloak_platform@0.1.10 snyk-protect F:\Kloak Information Technologies project - NDA\test\Kloak_platform-master
> snyk protect

Successfully applied Snyk patches

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

added 771 packages from 626 contributors and audited 775 packages in 596.621s
found 0 vulnerabilities

F:\Kloak Information Technologies project - NDA\test\Kloak_platform-master>
F:\Kloak Information Technologies project - NDA\test\Kloak_platform-master>
F:\Kloak Information Technologies project - NDA\test\Kloak_platform-master>
F:\Kloak Information Technologies project - NDA\test\Kloak_platform-master>
F:\Kloak Information Technologies project - NDA\test\Kloak_platform-master>npm run start

> kloak_platform@0.1.10 start F:\Kloak Information Technologies project - NDA\test\Kloak_platform-master
> electron .

Terminate batch job (Y/N)? y

F:\Kloak Information Technologies project - NDA\test\Kloak_platform-master>node app\main fales true
Wed, 13 May 2020 17:40:30 GMT:
*************************** Kloak Platform [ 0.1.8 ] server start up *****************************
Access url: http://localhost:3000

Wed, 13 May 2020 17:40:42 GMT: socketServerConnected [3yeg-f6Pwpc0-KrhAAAA][ ::1] connect 0

socket.on ( 'keypair')

localServer on checkImap!
Wed, 13 May 2020 17:41:16 GMT: start test imap [qtgate_test3@icloud.com]

qtGateImap connect mail server [imap.mail.me.com: 993] setTimeout [10] !
imapAccountTest on end err =  Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
doingCheckImap Async.series Error! Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
^C
F:\Kloak Information Technologies project - NDA\test\Kloak_platform-master>node app\main fales true
Wed, 13 May 2020 17:54:33 GMT:
*************************** Kloak Platform [ 0.1.8 ] server start up *****************************
Access url: http://localhost:3000

Wed, 13 May 2020 17:54:33 GMT: socketServerConnected [PeGUw4P8HEsGl-5PAAAA][ ::1] connect 0

Wed, 13 May 2020 17:54:33 GMT: socketServerConnected [K4FwRiGsA85P-OaKAAAB][ ::1] connect 0

Wed, 13 May 2020 17:54:36 GMT: socketServerConnected [EZh2_afGMYNxBaJtAAAC][ ::1] connect 0

socket.on ( 'keypair')

Wed, 13 May 2020 17:54:46 GMT: socketServerConnected [W85svBmR8EiPSXTbAAAD][ ::1] connect 0

socket.on ( 'keypair')

Wed, 13 May 2020 17:59:35 GMT: socketServerConnected [63HJ0to1dEuElNT8AAAE][ ::1] connect 0

socket.on ( 'keypair')

Wed, 13 May 2020 18:00:37 GMT: socketServerConnected [HlOe_rHir6sD-HAOAAAF][ ::1] connect 0

socket.on ( 'keypair')

Wed, 13 May 2020 18:04:07 GMT: socketServerConnected [WV9ULWrVdmVpYAc2AAAG][ ::1] connect 0

Wed, 13 May 2020 18:05:52 GMT: socketServerConnected [334swgvLvpFitGZMAAAH][ ::1] connect 0

Wed, 13 May 2020 18:05:52 GMT: socketServerConnected [sbsNGQfgTluV2i0oAAAI][ ::1] connect 0

Wed, 13 May 2020 18:05:52 GMT: socketServerConnected [CK4YYcMQE0gMNcKwAAAJ][ ::1] connect 0

Wed, 13 May 2020 18:05:52 GMT: socketServerConnected [fPbINbO8QmFdcqe6AAAK][ ::1] connect 0

Wed, 13 May 2020 18:05:52 GMT: socketServerConnected [5a7OCo2OQe26o8h8AAAL][ ::1] connect 0

^C
F:\Kloak Information Technologies project - NDA\test\Kloak_platform-master>node app\main flase true
Wed, 13 May 2020 18:06:34 GMT:
*************************** Kloak Platform [ 0.1.8 ] server start up *****************************
Access url: http://localhost:3000

Wed, 13 May 2020 18:06:42 GMT: socketServerConnected [CykZVQt4YeKEIj1wAAAA][ ::1] connect 0

socket.on ( 'keypair')

localServer on checkImap!
Wed, 13 May 2020 18:07:25 GMT: start test imap [qtgate_test3@icloud.com]

qtGateImap connect mail server [17.56.8.133: 993] setTimeout [10] !
(node:16748) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
imapAccountTest on end err =  Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: IP: 17.56.8.133 is not in the cert's list:
    at Object.checkServerIdentity (tls.js:279:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1331:27)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
  reason: "IP: 17.56.8.133 is not in the cert's list: ",
  host: '17.56.8.133',
  cert: {
    subject: [Object: null prototype] {
      CN: 'imap.mail.me.com',
      OU: 'management:idms.group.859635',
      O: 'Apple Inc.',
      ST: 'California',
      C: 'US'
    },
    issuer: [Object: null prototype] {
      CN: 'Apple IST CA 2 - G1',
      OU: 'Certification Authority',
      O: 'Apple Inc.',
      C: 'US'
    },
    subjectaltname: 'DNS:imap.mail.me.com, DNS:mail.me.com, DNS:mail.mac.com, DNS:p01-imap.mail.me.com, DNS:p02-imap.mail.me.com, DNS:p03-imap.mail.me.com, DNS:p04-imap.mail.me.com, DNS:p05-imap.mail.me.com, DNS:p06-imap.mail.me.com, DNS:p07-imap.mail.me.com, DNS:p08-imap.mail.me.com, DNS:p09-imap.mail.me.com, DNS:p10-imap.mail.me.com, DNS:p11-imap.mail.me.com, DNS:p12-imap.mail.me.com, DNS:p13-imap.mail.me.com, DNS:p14-imap.mail.me.com, DNS:p15-imap.mail.me.com, DNS:p16-imap.mail.me.com, DNS:p17-imap.mail.me.com, DNS:p18-imap.mail.me.com, DNS:p19-imap.mail.me.com, DNS:p20-imap.mail.me.com, DNS:p21-imap.mail.me.com, DNS:p22-imap.mail.me.com, DNS:p23-imap.mail.me.com, DNS:p24-imap.mail.me.com, DNS:p25-imap.mail.me.com, DNS:p26-imap.mail.me.com, DNS:p27-imap.mail.me.com, DNS:p28-imap.mail.me.com, DNS:p29-imap.mail.me.com, DNS:p30-imap.mail.me.com, DNS:p31-imap.mail.me.com, DNS:p32-imap.mail.me.com, DNS:p33-imap.mail.me.com, DNS:p34-imap.mail.me.com, DNS:p35-imap.mail.me.com, DNS:p36-imap.mail.me.com, DNS:p37-imap.mail.me.com, DNS:p38-imap.mail.me.com, DNS:p39-imap.mail.me.com, DNS:p40-imap.mail.me.com, DNS:p41-imap.mail.me.com, DNS:p42-imap.mail.me.com, DNS:p43-imap.mail.me.com, DNS:p44-imap.mail.me.com, DNS:p45-imap.mail.me.com, DNS:p46-imap.mail.me.com, DNS:p47-imap.mail.me.com, DNS:p48-imap.mail.me.com, DNS:p49-imap.mail.me.com, DNS:p50-imap.mail.me.com, DNS:p51-imap.mail.me.com, DNS:p52-imap.mail.me.com, DNS:p53-imap.mail.me.com, DNS:p54-imap.mail.me.com, DNS:p55-imap.mail.me.com, DNS:p56-imap.mail.me.com, DNS:p57-imap.mail.me.com, DNS:p58-imap.mail.me.com, DNS:p59-imap.mail.me.com, DNS:p60-imap.mail.me.com, DNS:p61-imap.mail.me.com, DNS:p62-imap.mail.me.com, DNS:p63-imap.mail.me.com, DNS:p64-imap.mail.me.com, DNS:p65-imap.mail.me.com, DNS:p66-imap.mail.me.com, DNS:p67-imap.mail.me.com, DNS:p68-imap.mail.me.com, DNS:p69-imap.mail.me.com, DNS:p70-imap.mail.me.com, DNS:p71-imap.mail.me.com, DNS:p72-imap.mail.me.com, DNS:p73-imap.mail.me.com, DNS:p74-imap.mail.me.com, DNS:p75-imap.mail.me.com, DNS:p76-imap.mail.me.com, DNS:p77-imap.mail.me.com, DNS:p78-imap.mail.me.com, DNS:p79-imap.mail.me.com, DNS:p80-imap.mail.me.com, DNS:p97-imap.mail.me.com, DNS:p98-imap.mail.me.com',
    infoAccess: [Object: null prototype] {
      'CA Issuers - URI': [Array],
      'OCSP - URI': [Array]
    },
    modulus: 'C05948178B60E16277DBABD9C332B23BFE757FB1CB7C4C494A202F598CCEA90FE12693EAA38FF3B4498DBDFBE8FB293237227D192D4F4C2D33FC702D56988292B3A5AC2A9E9C1234329F0D88C13F17A5100406E9796C5BCD28102566CEA2D5ED73ADAE3B1EFF2010C2D3D6EC4A39DF0CE7EFD19EDA80F78155831478D98A675FA2AE3203760820923C07E8642EAC9F040C8F0F5C2982C723BC3C74BDA999E660848E6F7C7A603FF694EA65F55CC1DCC972F313B407DC2EBDAEBC82ABE03B502434B977F31DE13F9BEB4DD653057C0C84943C579836B3301BA6FD7163F7BF309AAB4AE9B65FDD195545A1AB50CEF63CE1649500A6BA10EDAE24351ED5F8782217',
    bits: 2048,
    exponent: '0x10001',
    pubkey: <Buffer 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f 00 30 82 01 0a 02 82 01 01 00 c0 59 48 17 8b 60 e1 62 77 db ab d9 c3 32 b2 3b fe ... 244 more bytes>,
    valid_from: 'Mar 18 21:28:01 2019 GMT',
    valid_to: 'Apr 16 21:28:01 2021 GMT',
    fingerprint: 'E1:A5:F9:D2:2A:81:09:79:CA:CD:FC:0B:41:51:F5:61:E8:D0:29:76',
    fingerprint256: '33:6B:9F:46:EE:CE:07:E8:17:F9:F4:ED:B4:B2:4E:EE:92:65:2C:88:66:57:95:99:23:C5:AB:BC:F6:1E:6B:C6',
    ext_key_usage: [ '1.3.6.1.5.5.7.3.2', '1.3.6.1.5.5.7.3.1' ],
    serialNumber: '62CBBFC566127C4758E96BDBC38EC9E6',
    raw: <Buffer 30 82 0f 61 30 82 0e 49 a0 03 02 01 02 02 10 62 cb bf c5 66 12 7c 47 58 e9 6b db c3 8e c9 e6 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 62 31 1c ... 3891 more bytes>,
    issuerCertificate: {
      subject: [Object: null prototype],
      issuer: [Object: null prototype],
      infoAccess: [Object: null prototype],
      modulus: 'D093A11D47432016B20B6BEBC3D5B4E8C798CDF3DEBFE84DE9E3368007FC451B6A7C4586AE56D3A4097F610D6B5D7E526B7DB4C839C4F4673AF783CE196F862F7E457E471C6752CA95055DE2365185C0D46780356F15DD3EFD1DD2FD8F3450D8EC762ABEE3D3DAE4FDC8EB280296119717611CE9C4593B42DC32D1091DDAA6D14386FF5EB2BC8CCF66DB018B02AE9448F3388FFDEA32A808EC86975194243E49499653E879A14081E905BB939551FCE3FD7C114BF79E08B315491507F9D137A09B4B32F6B5C4DC6AD1FC0AEDF6E0C529A0A88B71FE0D92BCFE5470180A6DC7ED0CFBC92D06C38C85FCCB865CD6368E128B097FFB191A38D5F094307A0FA68CF3',
      bits: 2048,
      exponent: '0x10001',
      pubkey: <Buffer 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f 00 30 82 01 0a 02 82 01 01 00 d0 93 a1 1d 47 43 20 16 b2 0b 6b eb c3 d5 b4 e8 c7 ... 244 more bytes>,
      valid_from: 'Jun 16 15:42:02 2014 GMT',
      valid_to: 'May 20 15:42:02 2022 GMT',
      fingerprint: '8E:83:21:CA:08:B0:8E:37:26:FE:1D:82:99:68:84:EE:B5:F0:D6:55',
      fingerprint256: 'AC:2B:92:2E:CF:D5:E0:17:11:77:2F:EA:8E:D3:72:DE:9D:1E:22:45:FC:E3:F5:7A:9C:DB:EC:77:29:6A:42:4B',
      serialNumber: '023A74',
      raw: <Buffer 30 82 04 40 30 82 03 28 a0 03 02 01 02 02 03 02 3a 74 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 42 31 0b 30 09 06 03 55 04 06 13 02 55 53 31 16 ... 1042 more bytes>,
      issuerCertificate: [Object]
    }
  },
  code: 'ERR_TLS_CERT_ALTNAME_INVALID'
}
doingCheckImap Async.series Error! Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: IP: 17.56.8.133 is not in the cert's list:
    at Object.checkServerIdentity (tls.js:279:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1331:27)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
  reason: "IP: 17.56.8.133 is not in the cert's list: ",
  host: '17.56.8.133',
  cert: {
    subject: [Object: null prototype] {
      CN: 'imap.mail.me.com',
      OU: 'management:idms.group.859635',
      O: 'Apple Inc.',
      ST: 'California',
      C: 'US'
    },
    issuer: [Object: null prototype] {
      CN: 'Apple IST CA 2 - G1',
      OU: 'Certification Authority',
      O: 'Apple Inc.',
      C: 'US'
    },
    subjectaltname: 'DNS:imap.mail.me.com, DNS:mail.me.com, DNS:mail.mac.com, DNS:p01-imap.mail.me.com, DNS:p02-imap.mail.me.com, DNS:p03-imap.mail.me.com, DNS:p04-imap.mail.me.com, DNS:p05-imap.mail.me.com, DNS:p06-imap.mail.me.com, DNS:p07-imap.mail.me.com, DNS:p08-imap.mail.me.com, DNS:p09-imap.mail.me.com, DNS:p10-imap.mail.me.com, DNS:p11-imap.mail.me.com, DNS:p12-imap.mail.me.com, DNS:p13-imap.mail.me.com, DNS:p14-imap.mail.me.com, DNS:p15-imap.mail.me.com, DNS:p16-imap.mail.me.com, DNS:p17-imap.mail.me.com, DNS:p18-imap.mail.me.com, DNS:p19-imap.mail.me.com, DNS:p20-imap.mail.me.com, DNS:p21-imap.mail.me.com, DNS:p22-imap.mail.me.com, DNS:p23-imap.mail.me.com, DNS:p24-imap.mail.me.com, DNS:p25-imap.mail.me.com, DNS:p26-imap.mail.me.com, DNS:p27-imap.mail.me.com, DNS:p28-imap.mail.me.com, DNS:p29-imap.mail.me.com, DNS:p30-imap.mail.me.com, DNS:p31-imap.mail.me.com, DNS:p32-imap.mail.me.com, DNS:p33-imap.mail.me.com, DNS:p34-imap.mail.me.com, DNS:p35-imap.mail.me.com, DNS:p36-imap.mail.me.com, DNS:p37-imap.mail.me.com, DNS:p38-imap.mail.me.com, DNS:p39-imap.mail.me.com, DNS:p40-imap.mail.me.com, DNS:p41-imap.mail.me.com, DNS:p42-imap.mail.me.com, DNS:p43-imap.mail.me.com, DNS:p44-imap.mail.me.com, DNS:p45-imap.mail.me.com, DNS:p46-imap.mail.me.com, DNS:p47-imap.mail.me.com, DNS:p48-imap.mail.me.com, DNS:p49-imap.mail.me.com, DNS:p50-imap.mail.me.com, DNS:p51-imap.mail.me.com, DNS:p52-imap.mail.me.com, DNS:p53-imap.mail.me.com, DNS:p54-imap.mail.me.com, DNS:p55-imap.mail.me.com, DNS:p56-imap.mail.me.com, DNS:p57-imap.mail.me.com, DNS:p58-imap.mail.me.com, DNS:p59-imap.mail.me.com, DNS:p60-imap.mail.me.com, DNS:p61-imap.mail.me.com, DNS:p62-imap.mail.me.com, DNS:p63-imap.mail.me.com, DNS:p64-imap.mail.me.com, DNS:p65-imap.mail.me.com, DNS:p66-imap.mail.me.com, DNS:p67-imap.mail.me.com, DNS:p68-imap.mail.me.com, DNS:p69-imap.mail.me.com, DNS:p70-imap.mail.me.com, DNS:p71-imap.mail.me.com, DNS:p72-imap.mail.me.com, DNS:p73-imap.mail.me.com, DNS:p74-imap.mail.me.com, DNS:p75-imap.mail.me.com, DNS:p76-imap.mail.me.com, DNS:p77-imap.mail.me.com, DNS:p78-imap.mail.me.com, DNS:p79-imap.mail.me.com, DNS:p80-imap.mail.me.com, DNS:p97-imap.mail.me.com, DNS:p98-imap.mail.me.com',
    infoAccess: [Object: null prototype] {
      'CA Issuers - URI': [Array],
      'OCSP - URI': [Array]
    },
    modulus: 'C05948178B60E16277DBABD9C332B23BFE757FB1CB7C4C494A202F598CCEA90FE12693EAA38FF3B4498DBDFBE8FB293237227D192D4F4C2D33FC702D56988292B3A5AC2A9E9C1234329F0D88C13F17A5100406E9796C5BCD28102566CEA2D5ED73ADAE3B1EFF2010C2D3D6EC4A39DF0CE7EFD19EDA80F78155831478D98A675FA2AE3203760820923C07E8642EAC9F040C8F0F5C2982C723BC3C74BDA999E660848E6F7C7A603FF694EA65F55CC1DCC972F313B407DC2EBDAEBC82ABE03B502434B977F31DE13F9BEB4DD653057C0C84943C579836B3301BA6FD7163F7BF309AAB4AE9B65FDD195545A1AB50CEF63CE1649500A6BA10EDAE24351ED5F8782217',
    bits: 2048,
    exponent: '0x10001',
    pubkey: <Buffer 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f 00 30 82 01 0a 02 82 01 01 00 c0 59 48 17 8b 60 e1 62 77 db ab d9 c3 32 b2 3b fe ... 244 more bytes>,
    valid_from: 'Mar 18 21:28:01 2019 GMT',
    valid_to: 'Apr 16 21:28:01 2021 GMT',
    fingerprint: 'E1:A5:F9:D2:2A:81:09:79:CA:CD:FC:0B:41:51:F5:61:E8:D0:29:76',
    fingerprint256: '33:6B:9F:46:EE:CE:07:E8:17:F9:F4:ED:B4:B2:4E:EE:92:65:2C:88:66:57:95:99:23:C5:AB:BC:F6:1E:6B:C6',
    ext_key_usage: [ '1.3.6.1.5.5.7.3.2', '1.3.6.1.5.5.7.3.1' ],
    serialNumber: '62CBBFC566127C4758E96BDBC38EC9E6',
    raw: <Buffer 30 82 0f 61 30 82 0e 49 a0 03 02 01 02 02 10 62 cb bf c5 66 12 7c 47 58 e9 6b db c3 8e c9 e6 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 62 31 1c ... 3891 more bytes>,
    issuerCertificate: {
      subject: [Object: null prototype],
      issuer: [Object: null prototype],
      infoAccess: [Object: null prototype],
      modulus: 'D093A11D47432016B20B6BEBC3D5B4E8C798CDF3DEBFE84DE9E3368007FC451B6A7C4586AE56D3A4097F610D6B5D7E526B7DB4C839C4F4673AF783CE196F862F7E457E471C6752CA95055DE2365185C0D46780356F15DD3EFD1DD2FD8F3450D8EC762ABEE3D3DAE4FDC8EB280296119717611CE9C4593B42DC32D1091DDAA6D14386FF5EB2BC8CCF66DB018B02AE9448F3388FFDEA32A808EC86975194243E49499653E879A14081E905BB939551FCE3FD7C114BF79E08B315491507F9D137A09B4B32F6B5C4DC6AD1FC0AEDF6E0C529A0A88B71FE0D92BCFE5470180A6DC7ED0CFBC92D06C38C85FCCB865CD6368E128B097FFB191A38D5F094307A0FA68CF3',
      bits: 2048,
      exponent: '0x10001',
      pubkey: <Buffer 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f 00 30 82 01 0a 02 82 01 01 00 d0 93 a1 1d 47 43 20 16 b2 0b 6b eb c3 d5 b4 e8 c7 ... 244 more bytes>,
      valid_from: 'Jun 16 15:42:02 2014 GMT',
      valid_to: 'May 20 15:42:02 2022 GMT',
      fingerprint: '8E:83:21:CA:08:B0:8E:37:26:FE:1D:82:99:68:84:EE:B5:F0:D6:55',
      fingerprint256: 'AC:2B:92:2E:CF:D5:E0:17:11:77:2F:EA:8E:D3:72:DE:9D:1E:22:45:FC:E3:F5:7A:9C:DB:EC:77:29:6A:42:4B',
      serialNumber: '023A74',
      raw: <Buffer 30 82 04 40 30 82 03 28 a0 03 02 01 02 02 03 02 3a 74 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 42 31 0b 30 09 06 03 55 04 06 13 02 55 53 31 16 ... 1042 more bytes>,
      issuerCertificate: [Object]
    }
  },
  code: 'ERR_TLS_CERT_ALTNAME_INVALID'
}

**Comment by KloakIT** [comment]
This error is happening because your anti-virus software's firewall is blocking IMAP and SMTP connections to the mail exchange server.  Please add IMAP server and SMTP server to the encrypted connection scanning exclusion's list if you are using Kaspersky or similar for other anti-virus software. This should resolve this issue.

**Comment by KloakIT** [comment]
Fixed
https://github.com/KloakIT/Kloak_platform/tree/092a47a9f9da4cbfe734901926fc73cbd74da040
